#项目端口号
server:
  address: 0.0.0.0
  port: 8121
  servlet:
    #上下文路径
    context-path: /api
    session:
      cookie:
        #cookie 30天过期（单位：s）
        max-age: 2592000

#spring基本配置
spring:
  application:
    name: yuoj-backend
  profiles:
    #选择配置文件
    active: dev

  #swagger配置
  mvc:
    pathmatch:
      matchingStrategy: ant_path_matcher


#mybatis配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除实体类字段名
      logic-delete-value: 1 #已删除逻辑值 1
      logic-not-delete-value: 0 #未删除逻辑值 0

#代码沙箱配置
codesandbox:
  type: example